import argparse
import json
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import auc, precision_recall_curve


SUPPORTED_DATASETS = ["advbench", "toxicchat", "xstest", "security"]


def parse_args():
    parser = argparse.ArgumentParser(description="Run gradSafe threshold analysis and save threshold/PR plots.")
    parser.add_argument(
        "--scores-csv",
        required=True,
        help="Path to the detection scores CSV generated by detection.py.",
    )
    parser.add_argument(
        "--dataset",
        choices=SUPPORTED_DATASETS,
        required=True,
        help="Dataset used to generate the scores CSV.",
    )
    parser.add_argument(
        "--output-dir",
        default="baselines/gradSafe/outputs/threshold",
        help="Directory where threshold metrics and plots will be written.",
    )
    return parser.parse_args()


def slugify(value):
    return re.sub(r"[^A-Za-z0-9._-]+", "-", value).strip("-").lower()


def build_output_stem(dataset, scores_csv):
    stem = slugify(scores_csv.stem)
    dataset_prefix = f"{dataset}__"
    if stem.startswith(dataset_prefix):
        return stem
    return f"{dataset}__{stem}"


def build_ground_truth(dataset, df):
    if dataset in {"advbench", "security"}:
        return np.ones(len(df), dtype=int)
    if dataset == "toxicchat":
        if "toxicity" not in df.columns:
            raise ValueError("Expected 'toxicity' column in scores CSV for toxicchat.")
        return df["toxicity"].eq(1).astype(int).to_numpy()
    if dataset == "xstest":
        if "type" not in df.columns:
            raise ValueError("Expected 'type' column in scores CSV for xstest.")
        return df["type"].fillna("").str.contains("contrast", case=False).astype(int).to_numpy()
    raise ValueError(f"Unsupported dataset: {dataset}")


def compute_threshold_metrics(labels, scores):
    precision, recall, thresholds = precision_recall_curve(labels, scores)
    f1_scores = np.nan_to_num(2 * (precision[:-1] * recall[:-1]) / (precision[:-1] + recall[:-1]))

    if thresholds.size == 0:
        return {
            "precision": precision,
            "recall": recall,
            "thresholds": thresholds,
            "f1_scores": f1_scores,
            "best_index": None,
            "best_threshold": None,
            "max_f1": None,
            "precision_at_best": None,
            "recall_at_best": None,
            "auprc": float(auc(recall, precision)),
        }

    best_index = int(np.argmax(f1_scores))
    return {
        "precision": precision,
        "recall": recall,
        "thresholds": thresholds,
        "f1_scores": f1_scores,
        "best_index": best_index,
        "best_threshold": float(thresholds[best_index]),
        "max_f1": float(f1_scores[best_index]),
        "precision_at_best": float(precision[best_index]),
        "recall_at_best": float(recall[best_index]),
        "auprc": float(auc(recall, precision)),
    }


def plot_threshold_sweep(metrics, output_path):
    thresholds = metrics["thresholds"]
    if thresholds.size == 0:
        return

    precision = metrics["precision"][:-1]
    recall = metrics["recall"][:-1]
    f1_scores = metrics["f1_scores"]
    best_index = metrics["best_index"]

    plt.figure(figsize=(8, 5))
    plt.plot(thresholds, precision, label="Precision", linestyle="--")
    plt.plot(thresholds, recall, label="Recall")
    plt.plot(thresholds, f1_scores, label="F1")
    plt.scatter(thresholds[best_index], f1_scores[best_index], c="red", label="Best F1", zorder=3)
    plt.title("Threshold Sweep for sure")
    plt.xlabel("Threshold")
    plt.ylabel("Score")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(output_path)
    plt.close()


def plot_pr_curve(metrics, output_path):
    precision = metrics["precision"]
    recall = metrics["recall"]

    plt.figure(figsize=(6, 6))
    plt.plot(recall, precision, label="PR Curve")
    best_index = metrics["best_index"]
    if best_index is not None:
        plt.scatter(recall[best_index], precision[best_index], c="red", label="Best F1", zorder=3)
    plt.title("Precision-Recall Curve for sure")
    plt.xlabel("Recall")
    plt.ylabel("Precision")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(output_path)
    plt.close()


def main():
    args = parse_args()
    scores_csv = Path(args.scores_csv)
    df = pd.read_csv(scores_csv)

    if "sure" not in df.columns:
        raise ValueError(f"Score column 'sure' not found in {scores_csv}.")

    labels = build_ground_truth(args.dataset, df)
    metrics = compute_threshold_metrics(labels, df["sure"].to_numpy())

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    config_slug = build_output_stem(args.dataset, scores_csv)
    threshold_plot = output_dir / f"{config_slug}__sure__threshold_sweep.png"
    pr_plot = output_dir / f"{config_slug}__sure__pr_curve.png"
    summary_path = output_dir / f"{config_slug}__thresholds.json"

    plot_threshold_sweep(metrics, threshold_plot)
    plot_pr_curve(metrics, pr_plot)

    summary = {
        "dataset": args.dataset,
        "scores_csv": str(scores_csv),
        "outputs": {
            "sure": {
                "best_threshold": metrics["best_threshold"],
                "max_f1": metrics["max_f1"],
                "precision_at_best": metrics["precision_at_best"],
                "recall_at_best": metrics["recall_at_best"],
                "auprc": metrics["auprc"],
            }
        },
    }

    with summary_path.open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print(f"Saved threshold summary to {summary_path}")


if __name__ == "__main__":
    main()
